"""empty message

Revision ID: 02a531899b00
Revises: 
Create Date: 2020-07-15 20:14:45.876787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a531899b00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('_genres', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('seeking_venue', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('_genres', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('seeking_talent', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # insert test data into Venue Table
    op.execute('''
    insert into "Venue"
       (name, _genres, address, city, state, phone, website, facebook_link, seeking_talent, seeking_description, image_link)
       values
       ('The Musical Hop'
            ,'Jazz,Reggae,Swing,Classical,Folk'
            ,'1015 Folsom Street'
            ,'San Francisco'
            ,'CA'
            ,'123-123-1234'
            ,'https://www.themusicalhop.com'
            ,'https://www.facebook.com/TheMusicalHop'
            , True
            ,'We are on the lookout for a local artist to play every two weeks. Please call us.'
            , 'https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60'
       )
     ,
        ('The Dueling Pianos Bar'
            ,'Classical,R&B,Hip-Hop'
            ,'335 Delancey Street'
            ,'New York'
            ,'NY'
            ,'914-003-1132'
            ,'https://www.theduelingpianos.com'
            ,'https://www.facebook.com/theduelingpianos'
            , False
            , null
            ,'https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80'
       )
     ,
        ('Park Square Live Music & Coffee'
            ,'Rock n Roll,Jazz,Classical,Folk'
            ,'34 Whiskey Moore Ave'
            ,'San Francisco'
            ,'CA'
            ,'415-000-1234'
            ,'https://www.parksquarelivemusicandcoffee.com'
            ,'https://www.facebook.com/ParkSquareLiveMusicAndCoffee'
            , False
            , null
            ,'https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=747&q=80'
       )    ''')

    #insert test data into Artist Table
    op.execute('''
    insert into "Artist"
        (name,_genres,city,state,phone,website,facebook_link,seeking_venue,seeking_description,image_link)
        values
        ('Guns N Petals'
             ,'Rock n Roll'
             ,'San Francisco'
             ,'CA'
             ,'326-123-5000'
             ,'https://www.gunsnpetalsband.com'
             ,'https://www.facebook.com/GunsNPetals'
             , True
             ,'Looking for shows to perform at in the San Francisco Bay Area!'
             , 'https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80'
        )
      ,
         ('Matt Quevedo'
             ,'Jazz'
             ,'New York'
             ,'NY'
             ,'300-400-5000'
			 , null
             ,'https://www.facebook.com/mattquevedo923251523'
             , False
			 , null
             ,'https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=334&q=80'
        )
      ,
         ('The Wild Sax Band'
             ,'Jazz,Classical'
             ,'San Francisco'
             ,'CA'
             ,'432-325-5432'
			 , null
			 , null
             , False
			 , null
             ,'https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=794&q=80'
        )    ''')

    #insert test data into Show Table
    op.execute('''
    insert into "Show"
       (venue_id, artist_id, start_time )
       values
       (1, 1,'2019-05-21T21:30:00.000Z')
     ,
        (3, 2,'2019-06-15T23:00:00.000Z')
     ,
        (3, 3,'2035-04-01T20:00:00.000Z')
     ,
        (3, 3,'2035-04-08T20:00:00.000Z')
     ,
        (3, 3,'2035-04-15T20:00:00.000Z')
    ''')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    op.drop_table('Venue')
    op.drop_table('Artist')
    # ### end Alembic commands ###
